

#======================================
CREATE DATABASE movimentacao_bancaria;
#======================================
USE movimentacao_bancaria;
#======================================


banco (IDBANCO, NOME, NUMERO, _CONTAS, _VALORTOTAL)
CREATE TABLE banco (IDBANCO INT PRIMARY KEY AUTO_INCREMENT) ENGINE=INNODB DEFAULT CHARSET=LATIN1;
ALTER TABLE banco ADD NOME 			VARCHAR(120) 		NOT NULL UNIQUE;
ALTER TABLE banco ADD NUMERO 		INT(50) 				NOT NULL UNIQUE;
ALTER TABLE banco ADD _CONTAS  INT 	DEFAULT 0;
ALTER TABLE banco ADD _VALORTOTAL  DECIMAL(9,2) DEFAULT 0.0;

DROP TRIGGER IF EXISTS antes_inserir_banco; 
DELIMITER $$
CREATE TRIGGER antes_inserir_banco BEFORE INSERT ON banco FOR EACH ROW
BEGIN
	SET NEW.NOME = UPPER(NEW.NOME);		
END $$
DELIMITER ;

DROP TRIGGER IF EXISTS antes_alterar_banco; 
DELIMITER $$
CREATE TRIGGER antes_alterar_banco BEFORE UPDATE ON banco FOR EACH ROW
BEGIN
	SET NEW.NOME = UPPER(NEW.NOME);	
END $$
DELIMITER ;

#DELIMITER $$
#CREATE TRIGGER antes_deletar_banco BEFORE DELETE ON banco FOR EACH ROW
#BEGIN
	#sem ações
#END $$
#DELIMITER ;
 
#DELIMITER $$
#CREATE TRIGGER depois_inserir_banco AFTER INSERT ON banco FOR EACH ROW;
#BEGIN
	#sem ações
#END $$
#DELIMITER ;

#DELIMITER $$
#CREATE TRIGGER depois_alterar_banco AFTER UPDATE ON banco FOR EACH ROW;
#BEGIN
	#sem ações
#END $$
#DELIMITER ;

#DELIMITER $$
#CREATE TRIGGER depois_deletar_banco AFTER DELETE ON banco FOR EACH ROW;
#BEGIN
	#sem ações
#END $$
#DELIMITER ;

conta (IDCONTA, NUMERO, *IDBANCO, *IDCLIENTE, _SALDO)
CREATE TABLE conta(IDCONTA INT PRIMARY KEY AUTO_INCREMENT) ENGINE=INNODB DEFAULT CHARSET=LATIN1;
ALTER TABLE conta ADD NUMERO 		INT(50) 				NOT NULL;
ALTER TABLE conta ADD IDBANCO 		INT 					NOT NULL;
ALTER TABLE conta ADD IDCLIENTE  	INT 					NOT NULL;
ALTER TABLE conta ADD _SALDO 		DECIMAL(9,2)            DEFAULT 0.0;
ALTER TABLE conta ADD FOREIGN KEY (IDBANCO) REFERENCES banco (IDBANCO);
ALTER TABLE conta ADD FOREIGN KEY (IDCLIENTE) REFERENCES cliente (IDCLIENTE);


#DROP TRIGGER IF EXISTS antes_inserir_conta; 
#DELIMITER $$
#CREATE TRIGGER antes_inserir_conta BEFORE INSERT ON conta FOR EACH ROW;
#BEGIN
	#sem ações	
#END $$
#DELIMITER ;

#DELIMITER $$
#CREATE TRIGGER antes_alterar_conta BEFORE UPDATE ON conta FOR EACH ROW;
#BEGIN
	#sem ações
#END $$
#DELIMITER ;

#DELIMITER $$
#CREATE TRIGGER antes_deletar_conta BEFORE DELETE ON conta FOR EACH ROW;
#BEGIN
	#sem ações
#END $$
#DELIMITER ;

DROP TRIGGER IF EXISTS depois_inserir_conta;
DELIMITER $$
CREATE TRIGGER depois_inserir_conta AFTER INSERT ON conta FOR EACH ROW
BEGIN
	DECLARE v_CONTAS INT;
	DECLARE v_VALORTOTAL DECIMAL(9,2);	
	
	SELECT COUNT(*),SUM(_SALDO) INTO v_CONTAS,v_VALORTOTAL FROM conta WHERE IDBANCO=NEW.IDBANCO;
	UPDATE banco SET _CONTAS=v_CONTAS WHERE IDBANCO=NEW.IDBANCO;	
	UPDATE banco SET _VALORTOTAL = ROUND(v_VALORTOTAL, 2) WHERE IDBANCO=NEW.IDBANCO;
	
	SELECT COUNT(*),SUM(_SALDO) INTO v_CONTAS,v_VALORTOTAL FROM conta WHERE IDCLIENTE=NEW.IDCLIENTE;
	UPDATE cliente SET _CONTAS=v_CONTAS WHERE IDCLIENTE=NEW.IDCLIENTE;	
	UPDATE cliente SET _VALORTOTAL = ROUND(v_VALORTOTAL, 2) WHERE IDCLIENTE=NEW.IDCLIENTE;
	
END $$
DELIMITER ;


DROP TRIGGER IF EXISTS depois_alterar_conta;
DELIMITER $$
CREATE TRIGGER depois_alterar_conta AFTER UPDATE ON conta FOR EACH ROW
BEGIN
	DECLARE v_CONTAS INT;
	DECLARE v_VALORTOTAL DECIMAL(9,2);	
	
	SELECT COUNT(*),SUM(_SALDO) INTO v_CONTAS,v_VALORTOTAL FROM conta WHERE IDBANCO=NEW.IDBANCO;
	UPDATE banco SET _CONTAS=v_CONTAS WHERE IDBANCO=NEW.IDBANCO;	
	UPDATE banco SET _VALORTOTAL = ROUND(v_VALORTOTAL, 2) WHERE IDBANCO=NEW.IDBANCO;
	
	SELECT COUNT(*),SUM(_SALDO) INTO v_CONTAS,v_VALORTOTAL FROM conta WHERE IDCLIENTE=NEW.IDCLIENTE;
	UPDATE cliente SET _CONTAS=v_CONTAS WHERE IDCLIENTE=NEW.IDCLIENTE;	
	UPDATE cliente SET _VALORTOTAL = ROUND(v_VALORTOTAL, 2) WHERE IDCLIENTE=NEW.IDCLIENTE;

	SELECT COUNT(*),SUM(_SALDO) INTO v_CONTAS,v_VALORTOTAL FROM conta WHERE IDBANCO=OLD.IDBANCO;
	UPDATE banco SET _CONTAS=v_CONTAS WHERE IDBANCO=OLD.IDBANCO;	
	UPDATE banco SET _VALORTOTAL = ROUND(v_VALORTOTAL, 2) WHERE IDBANCO=OLD.IDBANCO;
	
	SELECT COUNT(*),SUM(_SALDO) INTO v_CONTAS,v_VALORTOTAL FROM conta WHERE IDCLIENTE=OLD.IDCLIENTE;
	UPDATE cliente SET _CONTAS=v_CONTAS WHERE IDCLIENTE=OLD.IDCLIENTE;	
	UPDATE cliente SET _VALORTOTAL = ROUND(v_VALORTOTAL, 2) WHERE IDCLIENTE=OLD.IDCLIENTE;
END $$
DELIMITER ;


DROP TRIGGER IF EXISTS depois_deletar_conta;
DELIMITER $$
CREATE TRIGGER depois_deletar_conta AFTER DELETE ON conta FOR EACH ROW
BEGIN
	DECLARE v_CONTAS INT;
	DECLARE v_VALORTOTAL DECIMAL(9,2);		
	
	SELECT COUNT(*),SUM(_SALDO) INTO v_CONTAS,v_VALORTOTAL FROM conta WHERE IDBANCO=OLD.IDBANCO;
	UPDATE banco SET _CONTAS=v_CONTAS WHERE IDBANCO=OLD.IDBANCO;	
	UPDATE banco SET _VALORTOTAL = ROUND(v_VALORTOTAL, 2) WHERE IDBANCO=OLD.IDBANCO;
	
	SELECT COUNT(*),SUM(_SALDO) INTO v_CONTAS,v_VALORTOTAL FROM conta WHERE IDCLIENTE=OLD.IDCLIENTE;
	UPDATE cliente SET _CONTAS=v_CONTAS WHERE IDCLIENTE=OLD.IDCLIENTE;	
	UPDATE cliente SET _VALORTOTAL = ROUND(v_VALORTOTAL, 2) WHERE IDCLIENTE=OLD.IDCLIENTE;
END $$
DELIMITER ;



cliente (IDCLIENTE, NOME, CPF, _CONTAS, _VALORTOTAL)
CREATE TABLE cliente(IDCLIENTE INT PRIMARY KEY AUTO_INCREMENT) ENGINE=INNODB DEFAULT CHARSET=LATIN1;
ALTER TABLE cliente ADD NOME 			VARCHAR(50) 			NOT NULL;
ALTER TABLE cliente ADD CPF 				INT(11) 				NOT NULL UNIQUE;
ALTER TABLE cliente ADD _CONTAS 			INT 					DEFAULT 0;
ALTER TABLE cliente ADD _VALORTOTAL 		DECIMAL(9,2) 		DEFAULT 0.0;


DROP TRIGGER IF EXISTS antes_inserir_cliente; 
DELIMITER $$
CREATE TRIGGER antes_inserir_cliente BEFORE INSERT ON cliente FOR EACH ROW
BEGIN
	SET NEW.NOME = UPPER(NEW.NOME);
END $$
DELIMITER ;

DROP TRIGGER IF EXISTS antes_alterar_cliente; 
DELIMITER $$
CREATE TRIGGER antes_alterar_cliente BEFORE UPDATE ON cliente FOR EACH ROW
BEGIN
	SET NEW.NOME = UPPER(NEW.NOME);	
END $$
DELIMITER ;
 
#DELIMITER $$
#CREATE TRIGGER antes_deletar_cliente BEFORE DELETE ON cliente FOR EACH ROW;
#BEGIN
	#sem ações
#END $$
#DELIMITER ;


#DELIMITER $$
#CREATE TRIGGER depois_inserir_cliente AFTER INSERT ON cliente FOR EACH ROW;
#BEGIN
	#sem ações	
#END $$
#DELIMITER ;

#DELIMITER $$
#CREATE TRIGGER depois_alterar_cliente AFTER UPDATE ON cliente FOR EACH ROW;
#BEGIN
	#sem ações	
#END $$
#DELIMITER ;

#DELIMITER $$
#CREATE TRIGGER depois_deletar_cliente AFTER DELETE ON cliente FOR EACH ROW;
#BEGIN
	#sem ações	
#END $$
#DELIMITER ;



deposito (IDDEPOSITO, DTDEPOSITO, *IDCONTA, VALOR)
CREATE TABLE deposito(IDDEPOSITO INT PRIMARY KEY AUTO_INCREMENT) ENGINE=INNODB DEFAULT CHARSET=LATIN1;
ALTER TABLE deposito ADD DTDEPOSITO  	DATE;
ALTER TABLE deposito ADD IDCONTA   		INT  					NOT NULL;
ALTER TABLE deposito ADD VALOR   		DECIMAL(9,2) 		 DEFAULT 0.0;
ALTER TABLE deposito ADD FOREIGN KEY (IDCONTA) REFERENCES conta (IDCONTA);

#DROP TRIGGER IF EXISTS antes_inserir_deposito; 
#DELIMITER $$
#CREATE TRIGGER antes_inserir_deposito BEFORE INSERT ON deposito FOR EACH ROW
#BEGIN
	#sem ações			
#END $$
#DELIMITER ;

#DELIMITER $$
#CREATE TRIGGER antes_alterar_deposito BEFORE UPDATE ON deposito FOR EACH ROW;
#BEGIN
	#sem ações
#END $$
#DELIMITER ;

#DELIMITER $$
#CREATE TRIGGER antes_deletar_deposito BEFORE DELETE ON deposito FOR EACH ROW;
#BEGIN
	#sem ações
#END $$
#DELIMITER ;

DROP TRIGGER IF EXISTS depois_inserir_deposito;
DELIMITER $$
CREATE TRIGGER depois_inserir_deposito AFTER INSERT ON deposito FOR EACH ROW
BEGIN
	UPDATE conta SET _SALDO=ROUND(_SALDO+NEW.VALOR, 2) WHERE IDCONTA=NEW.IDCONTA;
END $$
DELIMITER ;

DROP TRIGGER IF EXISTS depois_alterar_deposito;
DELIMITER $$
CREATE TRIGGER depois_alterar_deposito AFTER UPDATE ON deposito FOR EACH ROW
BEGIN
	UPDATE conta SET _SALDO=ROUND(_SALDO+NEW.VALOR, 2) WHERE IDCONTA=NEW.IDCONTA;
	UPDATE conta SET _SALDO=ROUND(_SALDO-OLD.VALOR, 2) WHERE IDCONTA=OLD.IDCONTA;
END $$
DELIMITER ;

DROP TRIGGER IF EXISTS depois_deletar_deposito;
DELIMITER $$
CREATE TRIGGER depois_deletar_deposito AFTER DELETE ON deposito FOR EACH ROW
BEGIN
	UPDATE conta SET _SALDO=ROUND(_SALDO-OLD.VALOR, 2) WHERE IDCONTA=OLD.IDCONTA;	
END $$
DELIMITER ;




saque (IDSAQUE, DTSAQUE, *IDCONTA, VALOR)
CREATE TABLE saque(IDSAQUE INT PRIMARY KEY AUTO_INCREMENT) ENGINE=INNODB DEFAULT CHARSET=LATIN1;
ALTER TABLE saque ADD DTSAQUE  			DATE;
ALTER TABLE saque ADD IDCONTA 			INT 		NOT NULL;
ALTER TABLE saque ADD VALOR  			DECIMAL(9,2) 	DEFAULT 0.0  NOT NULL;
ALTER TABLE saque ADD FOREIGN KEY (IDCONTA) REFERENCES conta (IDCONTA);

#DROP TRIGGER IF EXISTS antes_inserir_saque; 
#DELIMITER $$
#CREATE TRIGGER antes_inserir_saque BEFORE INSERT ON saque FOR EACH ROW;
#BEGIN
	#sem ações	
#END $$
DELIMITER ;

#DELIMITER $$
#CREATE TRIGGER antes_alterar_saque BEFORE UPDATE ON saque FOR EACH ROW;
#BEGIN
	#sem ações	
#END $$
#DELIMITER ;

#DELIMITER $$
#CREATE TRIGGER antes_deletar_saque BEFORE DELETE ON saque FOR EACH ROW;
#BEGIN
	#sem ações	
#END $$
#DELIMITER ;

DROP TRIGGER IF EXISTS depois_inserir_saque;
DELIMITER $$
CREATE TRIGGER depois_inserir_saque AFTER INSERT ON saque FOR EACH ROW
BEGIN
	UPDATE conta SET _SALDO=ROUND(_SALDO-NEW.VALOR, 2) WHERE IDCONTA=NEW.IDCONTA;	
END $$
DELIMITER ;

DROP TRIGGER IF EXISTS depois_alterar_saque;
DELIMITER $$
CREATE TRIGGER depois_alterar_saque AFTER UPDATE ON saque FOR EACH ROW
BEGIN
	UPDATE conta SET _SALDO=ROUND(_SALDO+NEW.VALOR, 2) WHERE IDCONTA=NEW.IDCONTA;	
	UPDATE conta SET _SALDO=ROUND(_SALDO+OLD.VALOR, 2) WHERE IDCONTA=OLD.IDCONTA;	
END $$
DELIMITER ;

DROP TRIGGER IF EXISTS depois_deletar_saque;
DELIMITER $$
CREATE TRIGGER depois_deletar_saque AFTER DELETE ON saque FOR EACH ROW
BEGIN
	UPDATE conta SET _SALDO=ROUND(_SALDO+OLD.VALOR, 2) WHERE IDCONTA=OLD.IDCONTA;
END $$
DELIMITER ;




